name: "SLSA verifier demo"
on:
  workflow_dispatch:
  
jobs:
  verify:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Verify artifact"
        uses: slsa-framework/slsa-verifier/actions/installer@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
